### ISSUE TITLE
Codeschool Ember is no longer free on codeschool

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/ember-study#103]
Only the Getting Started section of Codeschool Ember is available for free.  Update required reading to only require the free section.

https://github.com/ga-wdi-boston/ember-study/blob/master/study.md#required-viewing
>Additionally, we highly recommend completing the *entire* [Try Ember](https://www.codeschool.com/courses/try-ember) course from CodeSchool.

```diff
-Additionally, we highly recommend completing the *entire* [Try Ember](https://www.codeschool.com/courses/try-ember) course from CodeSchool.
+Additionally, we highly recommend completing the *Getting Started* section of [Try Ember](https://www.codeschool.com/courses/try-ember) course from CodeSchool.
```
>Additionally, we highly recommend completing the *Getting Started* section of [Try Ember](https://www.codeschool.com/courses/try-ember) course from CodeSchool.

**Comment by jrhorn424** [comment]
This is incorrect. When I say "recommend" I mean recommend, and I mean pay. It's never been free.

Recommend does not mean required.
