### ISSUE TITLE
Add instructions for installing Ember

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/ember-study#27]
ember-cli globally
bower globally
watchman

Remove from ember lesson.

issue opened via @jrhorn424

**Comment by gaand** [comment]
``` sh
npm install -g ember-cli
npm install -g bower
brew install watchman
```

Currently on linux, watchman must be installed from source.

**Comment by RealWeeks** [comment]
@gaand @jrhorn424 Do we trust the to do this on their own?

**Comment by jrhorn424** [comment]
It isn't about trust. If we include the full instructions from `ga-wdi-boston/ember`, due diligence has been done. @gaand ?

**Comment by gaand** [comment]
Installing should be something they can handle at this point in the cohort.

**Comment by MicFin** [comment]
@gaand Both of the required readings include those steps, I believe this can be closed.

https://guides.emberjs.com/v2.11.0/getting-started/
https://ember-cli.com/user-guide/#getting-started

**Comment by jrhorn424** [comment]
Thanks @MicFin.
