### ISSUE TITLE
Add link to Tom Dale's "Stop Breaking the Web"

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ember-study#5]
It drives home the point that Ember is URL driven, and most of the "magic" in Ember comes from how it intelligently figures things out from the URL. https://www.youtube.com/watch?v=BQ6at0addi4

**Comment by RealWeeks** [comment]
@jrhorn424 @MattB-GA-Boston Can this be closed. Matt, added it in the mentioned merge?

**Comment by gaand** [comment]
It's in the study.md.
