### ISSUE TITLE
Trim: Ember.js - Guides and Tutorials (yes, read them all)?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ember-study#86]
I think this is the biggest time suck. I've already added options to trim the tutorial. I think having them actually DO the tutorial is a better use of their time than reading any of this, but having them read all of this in one study IMHO is far, far too much for one study.

**Comment by jrhorn424** [comment]
This feels like a duplicate of #83 

I guess I'm saying I agree with #83
